DROP DATABASE IF EXISTS ACTVIDAD;
CREATE DATABASE ACTVIDAD;
USE ACTVIDAD;

CREATE TABLE USUARIOS(
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    PUESTO TEXT NOT NULL, 
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE PENDIENTES(
    ID_PENDIENTES INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION TEXT NOT NULL,
    FECHA TEXT NOT NULL,
    HORA TEXT NOT NULL,
    ESTADO INT NOT NULL,
    FK_ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_PENDIENTES),
    FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

INSERT INTO USUARIOS (NOMBRE, APELLIDO, PUESTO) VALUES ("Nombre de ejemplo 1", "Apellido de ejemplo 1", "Puesto de ejemplo 1");
INSERT INTO USUARIOS (NOMBRE, APELLIDO, PUESTO) VALUES ("Nombre de ejemplo 2", "Apellido de ejemplo 2", "Puesto de ejemplo 2");
INSERT INTO USUARIOS (NOMBRE, APELLIDO, PUESTO) VALUES ("Nombre de ejemplo 3", "Apellido de ejemplo 3", "Puesto de ejemplo 3");
INSERT INTO USUARIOS (NOMBRE, APELLIDO, PUESTO) VALUES ("Nombre de ejemplo 4", "Apellido de ejemplo 4", "Puesto de ejemplo 4");
INSERT INTO USUARIOS (NOMBRE, APELLIDO, PUESTO) VALUES ("Nombre de ejemplo 5", "Apellido de ejemplo 5", "Puesto de ejemplo 5");

INSERT INTO PENDIENTES VALUES (1,"Ejemplo 1", "10/10/2022", "10:35", 1, 1);
INSERT INTO PENDIENTES VALUES (2,"Ejemplo 2", "10/10/2022", "10:35", 2, 2);
INSERT INTO PENDIENTES VALUES (3,"Ejemplo 3", "10/10/2022", "10:35", 3, 3);
INSERT INTO PENDIENTES VALUES (4,"Ejemplo 4", "10/10/2022", "10:35", 1, 4);
INSERT INTO PENDIENTES VALUES (5,"Ejemplo 5", "10/10/2022", "10:35", 2, 5);

SELECT * FROM USUARIOS;
SELECT * FROM PENDIENTES;